### ISSUE TITLE
result.expires_in is in wrong js format

### ISSUE THREAD

**Issue by mbret** [rogebrd/dropbox-oauth-popup#61]
**Describe the bug**
The value returned by dropbox uses unix epoch instead of whatever js format is

**To Reproduce**
check the value

**Expected Behavior**
`new Date(Date.now() + (result.expires_in * 1000))`

**Actual Behavior**
`new Date(Date.now() + (result.expires_in))`

**Screenshots**

**Versions**
#54043fd58e6ab36e21fe1c70b00d3b7c98736400

**Comment by rogebrd** [comment]
This should be fixed in v2.0.2! Please let me know if this doesn't fix the issue
